api:
  dashboard: true
  # debug: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"
    http:
      #middlewares:
      #  - secureHeaders@file
      tls:
        certResolver: le-dns
        domains:
          - main: youerning.cn
            sans:
              - "*.youerning.cn"
              
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  le-dns:
    acme:
      email: admin@youerning.cn
      storage: acme.json
      keyType: EC384
      dnsChallenge:
        provider: acme-dns
